spring:
#  h2:
#    console:
#      path: /h2-console
#      enabled: true
#  datasource:
#    platform: h2
#    url: jdbc:h2:mem:trello;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=MYSQL
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver
  datasource:
    url: jdbc:mysql://localhost:3306/trello?verifyServerCertificate=false&useSSL=false
    username: mysql
    password: mysql
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create

logging:
  level:
    org:
      springframework:
        web: DEBUG