server:
  tomcat:
    max-connections: 8192
    max-threads: 200

spring:
  datasource:
    url: jdbc:mysql://mysql:3306/trello?verifyServerCertificate=false&useSSL=false
    username: mysql
    password: mysql
    driver-class-name: com.mysql.jdbc.Driver

logging:
  file: /prod/logs/bootapp/application.log
  level:
    org.springframework.web: INFO

debug: false